apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-pwexpirycheck
spec:
  schedule: "0/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-container
            image: nyuappsec/assign3-db:v0
            env:
              - name: MYSQL_ROOT_PASSWORD
                value: thisisatestthing.

              - name: MYSQL_DB
                value: GiftcardSiteDB

              - name: MYSQL_HOST
                value: mysql-service

            ports:
              - containerPort: 3306
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - mysql -u root -p${MYSQL_ROOT_PASSWORD} -D${MYSQL_DB} -h${MYSQL_HOST} -e "SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.global_variables where VARIABLE_NAME like 'default_password_lifetime';"
          restartPolicy: OnFailure
