
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: lab3space
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo "Hello from the Kubernetes cluster";
            - pwd; ls; cat jobschedule.py; echo "after check";
            - sleep 300;

          restartPolicy: OnFailure
